# Generated by Django 3.2 on 2021-04-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenador', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('especialidade', models.TextField()),
            ],
        ),
    ]
